apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-bootstrap
spec:
  resources:
    - name: plumbing-git
      type: git

    - name: bootstrap-image
      type: image
  tasks:
  - name: build-bootstrap
    taskRef:
      name: buildah
    resources:
      inputs:
        - name: source
          resource: plumbing-git
      outputs:
        - name: image
          resource: bootstrap-image
    params:
      - name: DOCKERFILE
        value: CI/tasks/bootstrap/image/Dockerfile
